### PR TITLE
Deploy app to TestFlight with Travis CI

### PR DESCRIPTION
**Pull request by hectorerb**
This PR automated app distribution to TestFlight using Travis CI

Ref: https://github.com/flyve-mdm/flyve-mdm-ios-inventory-agent/issues/21 and https://github.com/flyve-mdm/flyve-mdm-ios-inventory-agent/issues/17

### CODE REVIEW

**Comment by ajsb85** [comment]
@hectorerb if you are working on this PR and you want to send new updates, put the prefix WIP in the name of the PR. I already edited the title. 👍

**Comment by hectorerb** [comment]
@ajsb85 very good! 👍

**Comment by ajsb85** [comment]
This branch has conflicts that must be resolved

**Comment by ajsb85** [comment]
You can create file execute mode permissions in git:

https://stackoverflow.com/questions/21691202/how-to-create-file-execute-mode-permissions-in-git-on-windows

Then you can remove the chmod in the `before_script`

**Comment by hectorerb** [comment]
@ajsb85 Thanks! I'll check it

**Pull request merged**
