### PR TITLE
Update localizable strings

### PR DESCRIPTION
**Pull request by hectorerb**
## Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: [Conventional Commit](https://conventionalcommits.org/)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the new behavior?

Hi, @ajsb85 / @rafaelje 

This PR updates localizable strings

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

**Review by ajsb85 — APPROVED** [review]
Reviewed

**Comment by ajsb85** [comment]
You are downloading these resources manually?

**Comment by hectorerb** [comment]
@ajsb85 I used tx push for update localizables string on Transifex

**Comment by ajsb85** [comment]
@hectorerb But this is an action of the push to develop in the CI

**Comment by hectorerb** [comment]
@ajsb85 Yes, but I just pushed to update my local changes, From CI it will be done again

**Pull request merged**
