### PR TITLE
Adds theme of Jazzy for the code documentation

### PR DESCRIPTION
**Pull request by Gianfranco97**
Hi, @hectorerb  

This PR add a custom theme to integrate with github pages.

Close: https://github.com/flyve-mdm/flyve-mdm-press-kit/issues/22

### CODE REVIEW

**Comment by ajsb85** [comment]
Hi, @Gianfranco97 
Ignore from git the "Desktop Services Store" file (DS_Store).

**Comment by ajsb85** [comment]
Hi, @Gianfranco97 

This PR point to the develop branch.
Please change to gh-pages.

**Comment by Gianfranco97** [comment]
I know, that folder is necessary when generating the documentation of the code

**Review by ajsb85 — CHANGES_REQUESTED** [review]
Change the develop branch to gh-pages.

**Review by ajsb85 — APPROVED** [review]

**Pull request merged**
