### PR TITLE
Development section

### PR DESCRIPTION
**Pull request by Naylin15**
### Changes description
Create template for test reports
Add script to update version list
Add dropdown for development section
Add new folder structure

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [x] Docs have been added/updated

### Estimated time

|Assignee|:tomato:|
|:---|:---:|
|@Naylin15 |64|
|@Gianfranco97|6|
|@hectorerb|2|

### References

Closes #N/A 
Related #151 
Related #157  
Depends on #N/A

### CODE REVIEW

**Comment by Naylin15** [comment]
Working on the HTML template with the help of @Gianfranco97 

Draft

gif-image

**Comment by Naylin15** [comment]
I've been trying to test the plugin, while at it encountered some issues to run the tests

Finally, I'm testing the plugin and fixing the issues on it

**Comment by Naylin15** [comment]
Update:

Final look with the implementation of the test report plugin

captura de pantalla 2018-10-05 a la s 6 00 33 p m

captura de pantalla 2018-10-05 a la s 5 59 25 p m

**Review by hectorerb — APPROVED** [review]

**Review by hectorerb — CHANGES_REQUESTED** [review]
Check CircleCI please

**Comment by Naylin15** [comment]
Hi @hectorerb,

The CI is failing due to an issue with the links generated for the documentation, I must investigate what is happening there

Thank you

**Review by hectorerb — APPROVED** [review]

**Comment by Naylin15** [comment]
Hi, @ajsb85 @hectorerb 

The issue with the broken links #155 will be addressed in other PR

I'm merging this one since its changes are for the versioning and to add the new folder structure for the development section

Thank you

**Pull request merged**
