### PR TITLE
Create about screen

### LINKED ISSUE #69: Relicensing the Inventory Agent
Hi, @hectorerb 

Please change the license file and the headers to use the LGPL.

The LGPL and application stores have a few incompatibilities which means that you do not have the rights to distribute LGPL code on DRM-enabled AppStores or locked devices.

### PR DESCRIPTION
**Pull request by hectorerb**
Hi, @ajsb85 

This PR adds these changes:

- Create screen about us
- Prepare app version for release
- Renew apple certificates and provisioning
- Fix local push notification for iOS 9

close: https://github.com/flyve-mdm/flyve-mdm-ios-inventory-agent/issues/69

### CODE REVIEW

**Comment by ajsb85** [comment]
Hi, @hectorerb 

Could you provide a screenshot of this screen? for a better review.

**Comment by hectorerb** [comment]
simulator screen shot - iphone 8 plus - 2017-09-27 at 15 38 12

**Comment by ajsb85** [comment]
Nice @hectorerb please add these changes

**Edit the footer:** 

```
Inventory Agent, version 0.1.0, build 190.
Built on Tue Jul 11 21:58:40 2017. Last commit 77d2ea0.
© Teclib' 2017. Application released under GPLv3. Flyve MDM®
```

**Add a links for:**

Last commit: 77d2ea0
```
https://github.com/flyve-mdm/flyve-mdm-ios-inventory-agent/commit/77d2ea0
```
© Teclib'
http://teclib-edition.com/

GPLv3
https://www.gnu.org/licenses/gpl-3.0.en.html

Flyve MDM®
https://flyve-mdm.com/

For the Commit ID, slice from 0 to 6 the SHA1 in the env var `CIRCLE_SHA1`
The SHA1 hash for the current build’s last commit.

**Review by ajsb85 — CHANGES_REQUESTED** [review]
Good job

**Comment by hectorerb** [comment]
simulator screen shot - iphone 7 - 2017-09-28 at 14 39 59

**Comment by hectorerb** [comment]
Change space of the line-height

simulator screen shot - iphone 7 - 2017-09-28 at 16 21 29

**Comment by ajsb85** [comment]
@hectorerb Nice 👍🏻

**Review by rafaelje — APPROVED** [review]
Reviewed 👍

**Pull request merged**
